name: Weekly Data Extraction

on:
  schedule:
    - cron: '0 1 * * 1'  # Runs every Monday at 1:00 AM UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Grants permission to push changes

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run data extraction script
        run: python extract_data.py

      - name: Debug - Check Directory and Files
        run: |
          echo "Current Directory:"
          pwd
          echo "Listing All Files:"
          ls -R

      - name: Upload extracted data as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: extracted-data
          path: json/ee_rounds_123_en.json  # Ensure this path matches where your script saves the file

      - name: Commit and Push Extracted Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add json/ee_rounds_123_en.json
          git commit -m "Automated weekly data extraction" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
